### ISSUE TITLE
Rename k8s-nonprod-environments to cloud-platform-nonprod-environments

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/k8s-nonprod-environments#11]
**Background**
This brings it in line with our other repos

**Done when**
- [ ] Repo is renamed
- [ ] All the links and references are changed
- [ ] All the trial/test users are notified 
- [ ] Kalbir, Kerin, Mitch or Todd have signed off on the final change.

**Estimate**
2

**Comment by kalbir** [comment]
We can close this as it will be covered by https://waffle.io/ministryofjustice/cloud-platform/cards/5afab0406ebdac001e7aac79
